name: "Checkout repo and setup Go"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'
        check-latest: true
