name: "Setup Go"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 'stable'
        check-latest: true
    - name: install staticcheck
      run: make install-staticcheck
      shell: bash
