run:
  timeout: 10m

linters-settings:
  goimports:
    local-prefixes: github.com/exoscale
  revive:
    rules:
      - name: if-return
        disabled: true

linters:
  enable:
    - errcheck
    - exportloopref
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - unused
  disable-all: true
