run:
  timeout: 10m

linters-settings:
  golint:
    min-confidence: 0.3
  goimports:
    local-prefixes: github.com
  revive:
    rules:
      - name: if-return
        disabled: true

linters:
  enable:
    - deadcode
    - errcheck
    - exportloopref
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - structcheck
    - unused
    - varcheck
  disable-all: true
