name: "Release"
inputs:
  registry_username:
    description: 'registry username'
    required: false
  registry_password:
    description: 'registry password'
    required: false
  release_github_token:
    description: 'github token with permissions "Contents: read-write" on release repos'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3

    - name: Login to Docker Hub
      if: ${{ inputs.registry_username != '' }} && ${{ inputs.registry_password != '' }}
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Compute goreleaser cache key
      run: |
        echo "GORELEASER_CACHE_KEY=$(make --just-print install-goreleaser | tr --delete [:space:] | base32 --wrap 0)" >> $GITHUB_OUTPUT
      id: goreleaser-cache-key
      shell: bash

    - name: Cache goreleaser
      id: cache-goreleaser
      uses: actions/cache@v3
      with:
        path: /home/runner/go/bin/goreleaser
        key: ${{ steps.goreleaser-cache-key.outputs.GORELEASER_CACHE_KEY }}

    - name: Install goreleaser
      if: steps.cache-goreleaser.outputs.cache-hit != 'true'
      run: make install-goreleaser
      shell: bash

    - run: echo "$(go env GOPATH)/bin/" >> $GITHUB_PATH
      shell: bash

    - run: make release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.release_github_token }}
